// Extensive collection of positive phrases
const singleWordPhrases = [
  'Joy', 'Peace', 'Love', 'Faith', 'Grace', 'Calm', 'Trust',
  'Dream', 'Grow', 'Shine', 'Soar', 'Flow', 'Rise', 'Bloom',
  'Smile', 'Dance', 'Rest', 'Focus', 'Create', 'Imagine', 'Wonder', 'Believe',
  'Achieve', 'Thrive', 'Inspire', 'Connect', 'Embrace', 'Flourish', 'Radiate', 'Transcend',
  'Awaken', 'Abundance', 'Harmony', 'Serenity', 'Vitality', 'Clarity', 'Courage', 'Strength',
  'Wisdom', 'Gratitude', 'Balance', 'Freedom', 'Purpose', 'Passion', 'Energy', 'Bliss',
  'Magic', 'Miracle', 'Light', 'Spark', 'Radiance', 'Beauty', 'Wonder',
  'Awe', 'Space', 'Vastness', 'Infinity', 'Eternity', 'Timelessness', 'Presence', 'Mindfulness',
  'Awareness', 'Consciousness', 'Alignment', 'Oneness', 'Unity', 'Wholeness', 'Connection', 'Belonging',
  'Community', 'Compassion', 'Empathy', 'Tenderness', 'Warmth', 'Comfort',
  'Coziness', 'Silence', 'Tranquility', 'Stability', 'Steadiness', 'Foundation',
  'Support', 'Reliability', 'Dependability', 'Loyalty', 'Faithfulness', 'Commitment',
  'Dedication', 'Persistence', 'Perseverance', 'Diligence', 'Determination', 'Resolve', 'Willpower', 'Intention',
  'Vision', 'Insight', 'Intuition', 'Knowing', 'Understanding', 'Comprehension', 'Perception',
  'Discernment', 'Brilliance', 'Intelligence', 'Cleverness', 'Humor', 'Laughter',
  'Playfulness', 'Buoyancy', 'Levity', 'Ease', 'Relaxation', 'Release', 'Liberation',
  'Sovereignty', 'Autonomy', 'Independence', 'Competence', 'Mastery', 'Excellence', 'Genius',
  'Greatness', 'Magnificence', 'Grandeur', 'Splendor', 'Glory', 'Majesty', 'Nobility', 'Dignity',
  'Honor', 'Respect', 'Appreciation', 'Admiration', 'Amazement',
  'Astonishment', 'Rapture', 'Ecstasy', 'Euphoria', 'Elation', 'Delight', 'Glee', 'Gladness',
  'Happiness', 'Contentment', 'Satisfaction', 'Fulfillment', 'Completion', 'Integration', 'Synthesis', 'Synergy',
  'Resonance', 'Vibration', 'Frequency', 'Rhythm', 'Melody', 'Synchronicity', 'Fluidity', 'Adaptability',
  'Flexibility', 'Resilience', 'Bounce', 'Vigor', 'Verve', 'Vivacity', 'Vibrancy', 'Aliveness',
  'Power', 'Potency', 'Potentiality', 'Possibility', 'Promise', 'Potential', 'Prospect', 'Optimism',
  'Positivity', 'Affirmation', 'Blessings', 'Favor', 'Fortune', 'Prosperity', 'Plenty',
  'Wealth', 'Richness', 'Bounty', 'Fruition', 'Manifestation', 'Creation', 'Invention',
  'Innovation', 'Originality', 'Uniqueness', 'Distinctiveness', 'Individuality', 'Selfhood', 'Identity', 'Essence',
  'Nature', 'Soul', 'Spirit', 'Divinity', 'Sacredness', 'Holiness', 'Blessing', 'Virtue',
  'Goodness', 'Righteousness', 'Purity', 'Innocence', 'Simplicity', 'Transparency', 'Authenticity', 'Genuineness',
  'Sincerity', 'Honesty', 'Truth', 'Veracity', 'Fidelity', 'Adoration', 'Esteem', 'Regard',
  'Thankfulness', 'Recognition', 'Acknowledgment', 'Validation', 'Confirmation', 'Encouragement', 'Empowerment', 'Enablement',
  'Facilitation', 'Assistance', 'Aid', 'Help', 'Service', 'Contribution', 'Generosity', 'Giving',
  'Sharing', 'Charity', 'Benevolence', 'Goodwill', 'Friendliness', 'Amiability', 'Geniality', 'Coziness',
  'Solace', 'Consolation', 'Relief', 'Buoyancy', 
  'Expansion', 'Growth', 'Development', 'Progress', 'Advancement', 'Improvement', 'Betterment', 'Refinement',
  'Cultivation', 'Nurturance', 'Care', 'Mellowness', 'Smoothness',
  'Fluidity', 'Equilibrium', 'Symmetry', 'Proportion', 'Elegance', 'Poise', 'Stateliness', 'Brilliance',
  'Luminosity', 'Incandescence', 'Effulgence', 'Resplendence', 'Sparkle', 'Glitter', 'Shine',
  'Brightness', 'Lucidity', 'Translucence', 'Illumination', 'Enlightenment', 'Sagacity', 
  'Discovery', 'Uncovering', 'Emerging', 'Arising', 'Blossoming', 'Flourishing', 'Thriving', 'Prospering',
  'Abounding', 'Overflowing', 'Brimming', 'Fullness', 'Completeness', 'Totality', 'Integrity',
  'Wellness', 'Health', 'Robustness', 'Fortitude', 'Bravery', 'Valor',
  // New words from user input
  'Breathe', 'Pause', 'Heal', 'Enough', 'Expand', 
  'Unfold', 'Laugh', 'Surrender', 'Bloom', 'Wonder', 
  'Alive', 'Clarity', 'Ease', 'Brave', 'Spark', 'Cozy', 
  'Play', 'Move', 'Fly', 'Trust', 'Simple', 'Warmth', 'Free',
  'Safe', 'Secure', 'Mindful', 'Effortless', 'Vast', 
  'Awake', 'Connected', 'Kind', 'Lucid', 'Grounded', 'Playful', 'Sunlit', 'Rebirth',
  // New encouraging words
  'Worthy', 'Capable', 'Present', 'Cherished', 'Nourished',
  'Restore', 'Refresh', 'Gentle', 'Sweet', 'Patient',
  'Held', 'Protected', 'Supported', 'Treasured', 'Valuable',
  'Deserving', 'Flowering', 'Rooted', 'Centered', 'Balanced',
  'Nurture', 'Embrace', 'Cradle', 'Shelter', 'Anchor',
  'Steady', 'Stable', 'Constant', 'Reliable', 'Enduring',
  'Allowing', 'Accepting', 'Welcoming', 'Receiving', 'Permitting',
  'Renew', 'Recover', 'Replenish', 'Restore', 'Rejuvenate',
  'Tender', 'Mild', 'Delicate', 'Yielding', 'Mellow'
];

const twoWordPhrases = [
  'inner peace', 'joyful heart', 'vibrant life', 'deep breath', 'fresh start',
  'bright future', 'endless possibilities', 'infinite potential', 'positive energy', 'pure joy',
  'genuine smile', 'serene moment', 'perfect harmony', 'dynamic balance', 'creative flow',
  'passionate living', 'mindful presence', 'quiet strength', 'gentle power', 'brave heart',
  'strong spirit', 'wise soul', 'grateful attitude', 'abundant blessings', 'divine timing',
  'magical moments', 'beautiful chaos', 'peaceful warrior', 'luminous being', 
  'sacred journey', 'eternal beauty', 'radiant light', 'divine spark', 'infinite wonder',
  'golden hour', 'timeless soul', 'shimmering presence', 'ethereal grace',
  'boundless love', 'mystical journey', 'gentle whispers', 'sacred moment', 'radiant energy',
  'brilliant light', 'soul purpose', 'loving kindness', 'abundant joy', 'quiet strength',
  'eternal wisdom', 'graceful being', 'blessed path', 'perfect harmony', 'spiritual awakening',
  'peaceful mind', 'soulful connection', 'healing touch', 'eternal flame', 'magical existence',
  'divine protection', 'sacred trust', 'blissful surrender', 'loving awareness', 'mindful living',
  'grateful heart', 'endless compassion', 'radiant health', 'abundant wealth', 'joyful spirit',
  'limitless potential', 'powerful intention', 'divine guidance', 'inner knowing', 'sacred space',
  'higher purpose', 'manifest desires', 'divine feminine', 'sacred masculine', 'perfect balance',
  'healing energy', 'loving presence', 'infinite abundance', 'magical life', 'peaceful existence',
  'steady rhythm', 'divine order', 'magical synchronicity', 'perfect timing', 'infinite grace',
  'beautiful journey', 'spiritual growth', 'soul connection', 'divine love', 'healing light',
  'sacred heart', 'perfect peace', 'gentle strength', 'radiant joy', 'beautiful soul',
  'eternal bliss', 'magical presence', 'sacred union', 'healing touch', 'infinite compassion',
  'beautiful spirit', 'eternal love', 'magical moments', 'gentle reminder', 'radiant beauty',
  'beautiful being', 'magical life', 'sacred path', 'loving presence', 'quiet mind',
  'beautiful journey', 'eternal grace', 'sacred space', 'quiet surrender', 'sacred trust',
  'gentle soul', 'quiet joy', 'infinite blessings', 'magical existence', 'quiet power',
  'beautiful spirit', 'eternal peace', 'sacred connection', 'loving awareness', 'radiant soul',
  'divine protection', 'sacred heart', 'healing touch', 'divine guidance', 'sacred moment',
  'stunning simplicity', 'quiet confidence', 'inner wisdom', 'free spirit', 'bold love',
  'always becoming', 'sweet surrender', 'creative flow', 'deep roots', 'brave heart',
  'pure wonder', 'rise up', 'strong foundation', 'endless grace',
  'still waters', 'bright soul', 'vital energy', 'wild wonder',
  'always learning', 'calm center', 'begin again', 'quiet mind', 'sweet joy',
  'vibrant presence', 'gentle reminder', 'awaken fully', 'divine timing', 'bold dreams',
  'fully alive', 'heart open', 'small joys', 'inner light', 'soft strength',
  'wild heart', 'quiet power', 'brave soul', 'fresh start', 'pure joy',
  'just breathe', 'open heart', 'healing energy', 'faith always',
  'create beauty', 'worthy love', 'eyes forward', 'embrace yourself',
  'choose happiness', 'inner peace', 'endless wonder', 'keep hope',
  'radiate love', 'simple pleasures', 'abundant grace', 'bold moves', 'quiet reflection',
  'creative spirit', 'full presence', 'endless curiosity', 'wild dreams', 'deep breaths',
  'unfold gently', 'fierce grace', 'tender heart', 'mindful moment', 'sacred pause',
  'cherish today', 'strong roots', 'morning light', 'bright future',
  'quiet courage', 'imagine more', 'bloom anyway', 'grateful heart', 'beautiful mind',
  'trust timing', 'live now', 'seek light', 'brilliant you',
  'kindness matters', 'lasting peace', 'good enough', 'courage dear', 'onwards always',
  'soul shine', 'kind words', 'brave steps', 'open mind', 'rise again',
  'true self', 'light within', 'wild freedom', 'pure bliss', 'new horizons',
  'seek beauty', 'hold hope', 'love wins', 'choose wisely',
  // New phrases from user input
  'be here', 'stay soft', 'keep going', 'just breathe', 'feel joy', 
  'let go', 'slow down', 'shine bright', 'trust more', 'laugh loud', 
  'dream big', 'be kind', 'love wins', 'rise up', 
  'flow free', 'embrace change', 'enjoy now', 
  'chase light', 'smile more', 'walk gently', 'live slow', 'grow strong', 
  'hold hope', 'choose peace', 'rest easy', 'seek truth', 'stay wild', 
  'be brave', 'stay grounded', 'radiate love',
  'open sky', 'fresh breath', 'warm light', 'gentle waves', 'silent sun', 
  'trust self', 'lift soul', 'begin softly', 'glow gently', 'rise slow', 
  'love fully', 'feel light', 'peace inside', 
  'still now', 'hold love', 'deep breath', 'calm mind', 'listen softly', 
  'root down', 'free heart', 'let go', 'choose ease', 
  'walk lightly', 'flow inward', 'touch peace', 'soothe self', 'brave now',
  'mend slow', 'pause fully', 'speak kind', 'smile soft', 'stay bright', 
  'open heart', 'trust calm', 'see wide', 'feel soft', 'release fear', 
  'embrace now', 'rise kind',
  'feel now', 'go slow', 'move soft', 'honor peace', 
  'welcome silence', 'touch light', 'radiate joy', 'stay light', 'live open', 
  'breathe slow', 'stay true', 'feel safe', 'walk slow', 
  'rest deeply', 'embrace pause', 'hug stillness', 'notice beauty', 
  'unfold softly', 'be sunlight', 'hold now', 'savor breath',
  // New encouraging, soothing phrases
  'trust yourself', 'believe yourself', 'honor yourself', 'embrace yourself',
  'gentle steps', 'soft landing', 'safe harbor', 'warm embrace',
  'tender care', 'patient growth', 'steady progress', 'quiet courage',
  'nurture yourself', 'gentle reminder', 'sweet moment', 'peaceful presence',
  'worthy now', 'enough already', 'perfectly imperfect', 'beautifully flawed',
  'growing gently', 'healing slowly', 'moving forward', 'becoming you',
  'simply breathe', 'just notice', 'be present', 'stay grounded',
  'feel supported', 'receive love', 'accept help', 'allow grace',
  'create space', 'allow ease', 'find comfort', 'seek peace',
  'take rest', 'go slowly', 'pause here', 'breathe deeply',
  'release tension', 'soften shoulders', 'unclench jaw', 'relax hands'
];

const threeWordPhrases = [
  'just be you', 'follow your heart', 'live with purpose', 'breathe deeply now',
  'trust the process', 'embrace the journey', 'find your light', 'shine from within',
  'create with passion', 'love without fear', 'dance in joy',
  'believe in yourself', 'nurture your soul',
  'honor your truth', 'speak with kindness', 'listen with openness', 'give with generosity',
  'receive with gratitude', 'walk in grace', 'stand with courage', 'move with intention',
  'dream without limits', 'hope beyond reason', 'pray with faith', 'meditate in stillness',
  'act with integrity', 'lead with compassion', 'follow with wisdom', 'learn through experience',
  'teach by example', 'heal with love', 'transform through acceptance', 'evolve with consciousness',
  'expand your awareness', 'deepen your understanding', 'clarify your vision', 'purify your intentions',
  'strengthen your resolve', 'soften your heart', 'open your mind', 'ground your energy',
  'elevate your vibration', 'align your chakras', 'balance your elements', 'harmonize your life',
  'simplify your existence', 'amplify your gifts', 'magnify your blessings', 'multiply your abundance',
  'increase your prosperity', 'enhance your wellbeing', 'improve your health', 'boost your immunity',
  'nourish your body',
  'fulfill your desires', 'manifest your dreams', 'create your reality', 'design your future',
  'shape your destiny', 'craft your legacy', 'establish your foundation',
  'secure your freedom', 'protect your peace', 'preserve your energy',
  'invest your time', 'give your presence', 'share your wisdom',
  'offer your help', 'extend your kindness', 'spread your love', 'radiate your light',
  'emanate your essence', 'express your truth', 'voice your concerns', 'state your needs',
  'claim your power', 'own your story',
  'direct your focus', 'channel your energy', 'harness your strength', 'utilize your talents',
  'develop your skills', 'hone your craft', 'master your art', 'perfect your technique',
  'refine your approach', 'adjust your attitude', 'shift your perspective', 'change your mind',
  'transform your thinking', 'elevate your consciousness', 'expand your awareness', 'broaden your horizons',
  'deepen your understanding', 'enrich your knowledge', 'enhance your wisdom', 'increase your compassion',
  'cultivate your kindness', 'nurture your empathy', 'foster your connection', 'strengthen your bonds',
  'deepen your relationships', 'honor your commitments', 'keep your promises',
  'transcend your boundaries', 'surpass your expectations', 'exceed your potential', 'realize your dreams',
  'achieve your goals', 'accomplish your mission', 'fulfill your purpose', 'live your destiny',
  'embody your values', 'reflect your principles', 'demonstrate your integrity', 'show your character',
  'reveal your nature', 'express your uniqueness', 'celebrate your individuality', 'honor your authenticity',
  'embrace your wholeness', 'accept your imperfections', 'love your flaws', 'appreciate your quirks',
  'value your differences', 'treasure your gifts', 'cherish your talents', 'honor your genius',
  'respect your intelligence', 'admire your creativity', 'celebrate your accomplishments', 'acknowledge your growth',
  'recognize your progress', 'appreciate your journey', 'honor your struggles', 'respect your resilience',
  'acknowledge your strength', 'celebrate your courage', 'admire your bravery', 'appreciate your vulnerability',
  'honor your openness', 'respect your boundaries', 'value your privacy', 'protect your energy',
  'preserve your wellbeing', 'prioritize your health', 'maintain your balance', 'restore your harmony',
  'reclaim your power', 'remember your worth', 'know your value', 'trust your path',
  'follow your intuition', 'honor your insights', 'respect your knowing', 'trust your guidance',
  'follow your bliss', 'pursue your passion', 'live your purpose', 'fulfill your mission',
  'embrace your calling', 'answer your destiny', 'realize your potential', 'actualize your dreams',
  // New phrases from user input
  'you are enough', 'breathe and release', 'everything is temporary', 
  'love without fear', 'let it be', 'make it count', 'begin again now', 
  'joy is free', 'soft is strong', 'peace feels good', 'stay with it', 
  'small is beautiful', 'kindness always wins', 'keep it light', 'glow not grind', 
  'hold the moment', 'move with grace', 'let joy in', 'happiness is homemade', 
  'silence is golden', 'open your heart', 'remember to breathe',
  'trust your journey',
  'you are safe', 'everything flows freely', 'trust your breath', 'moments pass gently',
  'peace surrounds you', 'this is peace', 'let silence speak', 'you are grounded',
  'feel your rhythm', 'let it land', 'always becoming new', 'the present listens',
  'everything begins now', 'time holds space', 'kindness never fades', 'healing happens quietly',
  'there is light', 'let joy grow', 'root into now', 'this is softness',
  'i am worthy', 'i choose peace', 'i welcome joy', 'i am whole', 'i accept myself', 
  'i feel grateful', 'i am strong', 'i am light', 'i grow daily', 'i let go', 
  'i feel love', 'i am calm', 'i trust life', 'i create beauty', 'i radiate peace', 
  'i am safe', 'i am healing', 'i am enough', 'i am balanced',
  'i am kind', 'i believe in me', 'i feel alive', 'i move forward', 'i find peace', 
  'i deserve rest',
  // New encouraging, soothing, empowering phrases
  'you are loved', 'you are seen', 'you matter here', 'you deserve rest',
  'you are worthy', 'breathe in peace', 'exhale all worry', 'release all tension',
  'trust your wisdom', 'honor your needs', 'feel your strength', 'recognize your courage',
  'embrace your journey', 'celebrate small victories', 'take gentle steps', 'progress not perfection',
  'all feelings pass', 'this moment matters', 'find your rhythm', 'trust the process',
  'nurture your spirit', 'listen with love', 'speak your truth', 'set loving boundaries',
  'practice self compassion', 'embrace your humanity', 'you are supported', 'you are protected',
  'you deserve care', 'you create beauty', 'you inspire others', 'you bring light',
  'connect with joy', 'allow yourself rest', 'give yourself grace', 'trust your timing',
  'embrace your uniqueness', 'celebrate your growth', 'recognize your resilience', 'acknowledge your journey'
];

const fourWordPhrases = [
  'live in the moment', 'follow your inner light', 'trust in the process',
  'believe in your dreams', 'keep your heart open', 'find joy in simplicity',
  'see beauty in everything', 'walk the middle path', 'dance like nobody watching',
  'sing from your soul', 'speak your truth always', 'listen with your heart',
  'embrace all that is', 'accept what comes gracefully', 'surrender to divine timing',
  'flow with lifes river', 'rise with the sun', 'rest beneath the stars',
  'breathe into your center', 'ground in mother earth', 'soar through clear skies',
  'swim in cosmic consciousness', 'dive into divine love', 'bathe in golden light',
  'walk with quiet dignity', 'stand in your power', 'move with graceful intention',
  'act from pure love', 'choose the higher path', 'take the next step',
  'follow where joy leads', 'go where peace flows', 'be where love grows',
  'create with open heart', 'manifest with clear intention', 'transform through loving awareness',
  'evolve into higher consciousness', 'expand beyond limiting beliefs', 'transcend all human suffering',
  'transmute pain to wisdom', 'alchemize lead to gold', 'turn darkness into light',
  'find strength in vulnerability', 'discover power through surrender', 'see opportunity within challenge',
  'embrace both joy and sorrow', 'honor darkness and light', 'welcome beginnings and endings',
  'celebrate life and death', 'treasure giving and receiving', 'balance action and rest',
  'harmonize mind and body', 'integrate spirit and matter', 'unify heart and mind',
  'connect heaven and earth', 'bridge divine and human', 'weave sacred and mundane',
  'blend wisdom and compassion', 'marry strength and tenderness', 'unite courage and kindness',
  'pair passion and peace', 'combine focus and flow', 'balance structure and freedom',
  'harmonize tradition and innovation', 'integrate ancient and modern', 'honor roots and wings',
  'respect past and future', 'cherish old and new', 'value depth and breadth',
  'appreciate detail and wholeness', 'balance simplicity and complexity', 'honor singularity and plurality',
  'embrace uniqueness and commonality', 'celebrate diversity and unity', 'value individuality and community',
  'honor solitude and connection', 'treasure silence and expression', 'balance stillness and movement',
  'harmonize being and doing', 'integrate thinking and feeling', 'unify knowing and being',
  'marry wisdom and innocence', 'blend experience and wonder', 'unite knowledge and mystery',
  'pair certainty and curiosity', 'combine clarity and openness', 'balance conviction and flexibility',
  'harmonize determination and surrender', 'integrate persistence and acceptance', 'honor effort and grace',
  // New phrases from user input
  'you good human',
  'stay weird forever',
  'absolutely not today',
  'float like tofu',
  'smell the pixels',
  'joy is weird',
  '404 fear not found',
  'feel the soup',
  'hug a tree',
  'existential but okay',
  'light but spicy',
  'zero thoughts club',
  'mentally on cloud',
  'emotionally moisturized',
  'nice vibe detected',
  'moon says relax',
  'ghosting my doubts',
  'chop wood carry water', 
  'let thoughts pass', 
  'be like water', 
  'sit with silence', 
  'no rush just flow',
  'now is enough', 
  'clouds come go', 
  'return to breath', 
  'see without judging', 
  'one step one breath',
  'accept the moment', 
  'stillness speaks', 
  'joy is now', 
  'release control', 
  'be where you are',
  'rain falls anyway', 
  'do nothing beautifully', 
  'this too changes',
  'sit with storms', 
  'become the moment', 
  'no need to chase',
  'flow with everything', 
  'the tea is enough', 
  'be leaf not branch',
  'quiet is loud', 
  'nothing added needed', 
  'enough is enough',
  'one breath truth', 
  'stillness answers all', 
  'do not try be',
  'listen to silence', 
  'be soft always', 
  'return to return',
  'rest is not reward', 
  'every leaf dances', 
  'moonlight touches nothing', 
  'a cloud passes', 
  'roots dig world', 
  'i whisper time', 
  'still water holds', 
  'a breath becomes', 
  'sunlight waits on',
  'we are soft animals',
  'light drips morning sky',
  'wind whispers nothing stays',
  'you are more star',
  'no noise only clouds',
  'softly now world',
  'you bloom in shade',
  'held by sky untouched',
  'slow is the song',
  'even the moon rests',
  'be water not rush',
  // New encouraging, soothing, empowering phrases
  'you are deeply loved',
  'you are not alone',
  'this moment will pass',
  'take one step forward',
  'breathe into your heart',
  'trust in your strength',
  'you have inner wisdom',
  'your feelings are valid',
  'healing takes gentle time',
  'pause and breathe deeply',
  'find comfort in stillness',
  'you deserve gentle care',
  'you matter right now',
  'your presence is enough',
  'honor your own pace',
  'small steps still progress',
  'you are becoming you',
  'embrace your quiet strength',
  'your journey is sacred',
  'your light still shines',
  'hold yourself with kindness',
  'treat yourself with tenderness',
  'speak to yourself gently',
  'move at your pace'
];

export { singleWordPhrases, twoWordPhrases, threeWordPhrases, fourWordPhrases }; 