// Curated collection of beautiful, meaningful phrases for ambient display
const twoWordPhrases = [
  // Simple, beautiful actions - keeping only the best
  'be kind', 'trust timing', 'live now',
  
  // Encouraging and nurturing
  'trust yourself', 'believe yourself', 'honor yourself', 'embrace yourself',
  'gentle steps', 'soft landing', 'safe harbor', 'warm embrace',
  'tender care', 'patient growth', 'steady progress', 'quiet courage',
  'nurture yourself', 'sweet moment', 'peaceful presence', 'worthy now',
  'enough already', 'perfectly imperfect', 'beautifully flawed', 'growing gently',
  'healing slowly', 'moving forward', 'becoming you', 'simply breathe',
  'just notice', 'be present', 'stay grounded', 'feel supported',
  'receive love', 'accept help', 'allow grace', 'create space',
  'allow ease', 'find comfort', 'seek peace', 'take rest',
  'go slowly', 'pause here', 'breathe deeply', 'release tension',
  'soften shoulders', 'relax hands'
];

const threeWordPhrases = [
  // Core wisdom
  'just be you', 'follow your heart', 'live with purpose', 'breathe deeply now',
  'trust the process', 'embrace the journey', 'find your light', 'shine from within',
  'create with passion', 'love without fear', 'dance in joy',
  'believe in yourself', 'nurture your soul', 'honor your truth',
  'speak with kindness', 'listen with openness', 'give with generosity',
  'receive with gratitude', 'walk in grace', 'stand with courage',
  'move with intention', 'dream without limits', 'hope beyond reason',
  'act with integrity', 'lead with compassion', 'follow with wisdom',
  'learn through experience', 'teach by example', 'heal with love',
  'transform through acceptance', 'expand your awareness', 'deepen your understanding',
  'clarify your vision', 'strengthen your resolve', 'soften your heart',
  'open your mind', 'ground your energy', 'balance your elements',
  'harmonize your life', 'simplify your existence', 'amplify your gifts',
  'magnify your blessings', 'enhance your wellbeing', 'improve your health',
  'nourish your body', 'fulfill your desires', 'manifest your dreams',
  'create your reality', 'design your future', 'craft your legacy',
  'secure your freedom', 'protect your peace', 'preserve your energy',
  'share your wisdom', 'offer your help', 'extend your kindness',
  'spread your love', 'radiate your light', 'express your truth',
  'claim your power', 'own your story', 'direct your focus',
  'channel your energy', 'harness your strength', 'develop your skills',
  'master your art', 'refine your approach', 'shift your perspective',
  'change your mind', 'transform your thinking', 'expand your awareness',
  'broaden your horizons', 'deepen your understanding', 'enhance your wisdom',
  'increase your compassion', 'cultivate your kindness', 'nurture your empathy',
  'foster your connection', 'strengthen your bonds', 'honor your commitments',
  'keep your promises', 'realize your dreams', 'achieve your goals',
  'accomplish your mission', 'fulfill your purpose', 'live your destiny',
  'embody your values', 'demonstrate your integrity', 'show your character',
  'express your uniqueness', 'celebrate your individuality', 'honor your authenticity',
  'embrace your wholeness', 'accept your imperfections', 'love your flaws',
  'treasure your gifts', 'cherish your talents', 'respect your intelligence',
  'celebrate your accomplishments', 'acknowledge your growth', 'recognize your progress',
  'appreciate your journey', 'honor your struggles', 'respect your resilience',
  'acknowledge your strength', 'celebrate your courage', 'admire your bravery',
  'appreciate your vulnerability', 'honor your openness', 'respect your boundaries',
  'protect your energy', 'preserve your wellbeing', 'prioritize your health',
  'maintain your balance', 'restore your harmony', 'reclaim your power',
  'remember your worth', 'know your value', 'trust your path',
  'follow your intuition', 'honor your insights', 'trust your guidance',
  'follow your bliss', 'pursue your passion', 'live your purpose',
  'embrace your calling', 'realize your potential',
  
  // Beautiful simple phrases
  'you are enough', 'breathe and release', 'everything is temporary',
  'love without fear', 'let it be', 'make it count', 'begin again now',
  'joy is free', 'soft is strong', 'peace feels good', 'stay with it',
  'small is beautiful', 'kindness always wins', 'keep it light',
  'hold the moment', 'move with grace', 'let joy in', 'happiness is homemade',
  'silence is golden', 'open your heart', 'remember to breathe',
  'trust your journey', 'embrace the unknown', 'find your rhythm',
  'listen to silence', 'welcome each moment', 'choose your thoughts',
  'create your peace', 'honor your feelings', 'trust your timing',
  'allow your growth', 'celebrate small wins', 'practice self compassion',
  'give yourself grace', 'you are loved', 'you are worthy',
  'you are capable', 'you are enough', 'rest when needed',
  'grow at your pace', 'trust your process', 'honor your needs',
  'listen to your body', 'follow your heart', 'trust your instincts',
  'believe in yourself', 'you are brave', 'you are resilient',
  'you are beautiful', 'you are precious', 'take your time',
  'go at your pace', 'trust your wisdom', 'honor your truth',
  'speak your heart', 'live your values', 'follow your dreams',
  'trust your path', 'embrace your story'
];



const conversationalPhrases = [
  // Beautiful, poetic encouragement that flows naturally
  'everything will be okay',
  'it\'s never too late to begin again',
  'you\'re doing just fine',
  'you can make it through this',
  'you matter more than you know',
  'this feeling will pass',
  'you\'ve got this',
  'you are not broken',
  'you are becoming whole',
  'you are doing enough',
  'your best is enough',
  'be gentle with yourself',
  'you deserve kindness',
  'mistakes don\'t define you',
  'growth takes time',
  'you\'re allowed to feel',
  'healing is not a straight line',
  'some days are heavier and that\'s okay',
  'your feelings are valid',
  'you are worthy of love',
  'small steps still count',
  'you\'re braver than you think',
  'you\'re exactly where you need to be',
  'your story isn\'t finished yet',
  'you\'re allowed to start over',
  'every day brings a new beginning',
  'you belong here',
  'your voice matters',
  'you\'re not behind in life',
  'you are right on time',
  'you have the power to create',
  'your potential is still unfolding',
  'outgrowing things is part of growth',
  'change can be scary and still worth it',
  'you are enough just as you are',
  'trust your own timing',
  'progress is more important than perfection',
  'you deserve to rest',
  'you are becoming who you\'re meant to be',
  'today is a fresh start',
  'you\'re stronger than you know',
  'your journey is your own',
  'you are worth celebrating',
  'take it one step at a time',
  'you don\'t have to be perfect',
  'you\'re learning and that matters',
  'it\'s okay to change your mind',
  'you are worthy of good things',
  'you are enough right now',
  'becoming takes time trust it',
  'you\'re allowed to take up space',
  'you are loved and lovable',
  'you are doing better than you think',
  'there is still beauty ahead',
  'rest is productive too',
  'you are allowed to pause',
  'you are still growing even on quiet days',
  'no one else gets to define your pace',
  'breathing is enough right now',
  'you are not alone',
  'being still is not being lazy',
  'you are allowed to simply exist',
  'you don\'t need a reason to take a break',
  'slowness is not a weakness',
  'let go of the need to prove',
  'just breathing is enough right now',
  'you are safe to pause',
  'silence is also an answer',
  'you\'re allowed to not know',
  'you\'re more than what you do',
  'rest is a form of resistance',
  'you can begin again gently',
  'you carry so much give yourself credit',
  'even stillness can be sacred',
  'you\'re already whole',
  'you\'re allowed to let things be easy',
  'you don\'t have to do it all today',
  'let today be simple',
  'even the moon rests',
  'you can pause without apology',
  'the quiet moments matter too'
];

// Export all phrase collections
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { singleWordPhrases, twoWordPhrases, threeWordPhrases, conversationalPhrases };
} 
